### ISSUE TITLE
Results for VisA dataset

### ISSUE THREAD

**Issue by BingliangLi** [TheStarOfMSY/MoEAD#4]
![image](https://github.com/user-attachments/assets/5da0a3f8-8116-4531-b515-08073f13f0f0)
Maybe the checkpoint file is wrong?

**Comment by TheStarOfMSY** [comment]
This checkpoint is for the origin model version, and I have uploaded this version code in models/reconstructions/moead_o.py. In this version, I reused some laye rnormalizations because of my code error. However, it seems to ehance the model performance on VisA dataset.  When I correct this problem, the model just reach 92.5 in Image_level AUROC.

**Comment by TheStarOfMSY** [comment]
This issue has been a bit troubling for me, and I don't know how to explain the reasons for this difference. I have withdrawn this problematic checkpoint.

**Comment by BingliangLi** [comment]
I trained the model on VisA and the results are close to the paper.
